FROM node:20.12.1-alpine3.18 AS build-stage
RUN mkdir client
WORKDIR /client
COPY package.json .
COPY package-lock.json .
RUN npm install
RUN npm install -g serve
COPY . .
RUN npm run build
EXPOSE 3000
ENTRYPOINT [ "serve", "-s", "dist" ]

