version: "3.8"
services:
  database:
    image: mysql:8.0.35
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: maher
      MYSQL_DATABASE: techstore
    container_name: database
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-pmaher", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  
  server:
    build: ./server
    # command: "python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

  client:
    build: ./client
    ports: 
      - 3000:3000

volumes:
  data:
