INSERT INTO `TechStore`.`store_category` (`id`, `name`, `slug`, `thumbnail`, `parent_category_id`) values 
	(1, 'COMPUTERS', 'computers', '/store/images/categories/category_1.png', NULL),
	(2, 'COMPONENTS', 'components', '/store/images/categories/category_2.png', NULL),
	(3, 'ACCESSORIES', 'accessories', '/store/images/categories/category_3.png', NULL),
	(4, 'MONITORS', 'monitors', '/store/images/categories/category_4.png', NULL),
	(5, 'MODDING', 'modding', '/store/images/categories/category_5.png', NULL),
	(6, 'SMARTPHONES', 'smartphones', '/store/images/categories/category_6.png', NULL),
	(7, 'DIGITAL', 'digital', '/store/images/categories/category_7.png', NULL),
	(8, 'CONSOLES', 'consoles', '/store/images/categories/category_8.png', NULL),
	(9, 'PC GAMER', 'pc-gamer', '/store/images/categories/category_9.png',1),
	(10, 'LAPTOP', 'laptop', '/store/images/categories/category_10.png',1),
	(11, 'LIGHT GAMING', 'light-gaming', '/store/images/categories/category_11.png',1),
	(12, 'FULL SETUP', 'full-setup', '/store/images/categories/category_12.png',1),
	(13, 'EXTEME PC', 'exteme-pc', '/store/images/categories/category_13.png',1),
	(14, 'PC MULTIMEDIA', 'pc-multimedia', '/store/images/categories/category_14.png',1),
	(15, 'PC PRO EDITING', 'pc-pro-editing', '/store/images/categories/category_15.png',1),
	(16, 'PC PRO RENDERING', 'pc-pro-rendering', '/store/images/categories/category_16.png',1),
	(17, 'ALL IN ONE PC', 'all-in-one-pc', '/store/images/categories/category_17.png',1),
	(18, 'PROCESSOR', 'processor', '/store/images/categories/category_18.png',2),
	(19, 'COOLING', 'cooling', '/store/images/categories/category_19.png',2),
	(20, 'MOTHERBOARD', 'motherboard', '/store/images/categories/category_20.png',2),
	(21, 'RAM', 'ram', '/store/images/categories/category_21.png',2),
	(22, 'GRAPHIC CARD', 'graphic-card', '/store/images/categories/category_22.png',2),
	(23, 'POWER SUPLY', 'power-suply', '/store/images/categories/category_23.png',2),
	(24, 'STORAGE', 'storage', '/store/images/categories/category_24.png',2),
	(25, 'CASE', 'case', '/store/images/categories/category_25.png',2),
	(26, 'NETWORK CARD', 'network-card', '/store/images/categories/category_26.png',2),
	(27, 'FAN', 'fan', '/store/images/categories/category_27.png',2),
	(28, 'KEYBOARD', 'keyboard', '/store/images/categories/category_28.png',3),
	(29, 'MOUSE', 'mouse', '/store/images/categories/category_29.png',3),
	(30, 'MOUSE PAD', 'mouse-pad', '/store/images/categories/category_30.png',3),
	(31, 'HEADSET', 'headset', '/store/images/categories/category_31.png',3),
	(32, 'CONTROLLER', 'controller', '/store/images/categories/category_32.png',3),
	(33, 'CABLE & ADAPTER', 'cable-&-adapter', '/store/images/categories/category_33.png',3),
	(34, 'SPEAKER', 'speaker', '/store/images/categories/category_34.png',3),
	(35, 'GAMING CHAIR', 'gaming-chair', '/store/images/categories/category_35.png',3),
	(36, 'PROFESSIONAL MONITOR', 'professional-monitor', '/store/images/categories/category_36.png',4),
	(37, 'GAMING MONITOR', 'gaming-monitor', '/store/images/categories/category_37.png',4),
	(38, 'SCREEN SUPPORT', 'screen-support', '/store/images/categories/category_38.png',4),
	(39, 'RGB ACCESSORIES', 'rgb-accessories', '/store/images/categories/category_39.png',5),
	(40, 'GPU BACKPLATE', 'gpu-backplate', '/store/images/categories/category_40.png',5),
	(41, 'CABLE MOD', 'cable-mod', '/store/images/categories/category_41.png',5),
	(42, 'IPHONE', 'iphone', '/store/images/categories/category_42.png',6),
	(43, 'ANDROID', 'android', '/store/images/categories/category_43.png',6),
	(44, 'OPERATING SYSTEM', 'operating-system', '/store/images/categories/category_44.png',7),
	(45, 'SOFTWARE', 'software', '/store/images/categories/category_45.png',7),
	(46, 'GIFT CARD', 'gift-card', '/store/images/categories/category_46.png',7),
	(47, 'PC GAMES', 'pc-games', '/store/images/categories/category_47.png',7),
	(48, 'CONSOLE ACCESSORIES', 'console-accessories', '/store/images/categories/category_48.png',8),
	(49, 'PLAYSTATION', 'playstation', '/store/images/categories/category_49.png',8),
	(50, 'XBOX', 'xbox', '/store/images/categories/category_50.png',8);

