INSERT INTO "store_category" ("id", "name", "thumbnail", "parent_category_id") values 
	(1, 'COMPUTERS', '/store/images/categories/category_1.png', NULL),
	(2, 'COMPONENTS', '/store/images/categories/category_2.png', NULL),
	(3, 'ACCESSORIES', '/store/images/categories/category_3.png', NULL),
	(4, 'MONITORS', '/store/images/categories/category_4.png', NULL),
	(5, 'MODDING', '/store/images/categories/category_5.png', NULL),
	(6, 'SMARTPHONES', '/store/images/categories/category_6.png', NULL),
	(7, 'DIGITAL', '/store/images/categories/category_7.png', NULL),
	(8, 'CONSOLES', '/store/images/categories/category_8.png', NULL),
	(9, 'PC GAMER', '/store/images/categories/category_9.png',1),
	(10, 'LAPTOP', '/store/images/categories/category_10.png',1),
	(11, 'LIGHT GAMING', '/store/images/categories/category_11.png',1),
	(12, 'FULL SETUP', '/store/images/categories/category_12.png',1),
	(13, 'EXTEME PC', '/store/images/categories/category_13.png',1),
	(14, 'PC MULTIMEDIA', '/store/images/categories/category_14.png',1),
	(15, 'PC PRO EDITING', '/store/images/categories/category_15.png',1),
	(16, 'PC PRO RENDERING', '/store/images/categories/category_16.png',1),
	(17, 'ALL IN ONE PC', '/store/images/categories/category_17.png',1),
	(18, 'PROCESSOR', '/store/images/categories/category_18.png',2),
	(19, 'COOLING', '/store/images/categories/category_19.png',2),
	(20, 'MOTHERBOARD', '/store/images/categories/category_20.png',2),
	(21, 'RAM', '/store/images/categories/category_21.png',2),
	(22, 'GRAPHIC CARD', '/store/images/categories/category_22.png',2),
	(23, 'POWER SUPLY', '/store/images/categories/category_23.png',2),
	(24, 'STORAGE', '/store/images/categories/category_24.png',2),
	(25, 'CASE', '/store/images/categories/category_25.png',2),
	(26, 'NETWORK CARD', '/store/images/categories/category_26.png',2),
	(27, 'FAN', '/store/images/categories/category_27.png',2),
	(28, 'KEYBOARD', '/store/images/categories/category_28.png',3),
	(29, 'MOUSE', '/store/images/categories/category_29.png',3),
	(30, 'MOUSE PAD', '/store/images/categories/category_30.png',3),
	(31, 'HEADSET', '/store/images/categories/category_31.png',3),
	(32, 'CONTROLLER', '/store/images/categories/category_32.png',3),
	(33, 'CABLE & ADAPTER', '/store/images/categories/category_33.png',3),
	(34, 'SPEAKER', '/store/images/categories/category_34.png',3),
	(35, 'GAMING CHAIR', '/store/images/categories/category_35.png',3),
	(36, 'PROFESSIONAL MONITOR', '/store/images/categories/category_36.png',4),
	(37, 'GAMING MONITOR', '/store/images/categories/category_37.png',4),
	(38, 'SCREEN SUPPORT', '/store/images/categories/category_38.png',4),
	(39, 'RGB ACCESSORIES', '/store/images/categories/category_39.png',5),
	(40, 'GPU BACKPLATE', '/store/images/categories/category_40.png',5),
	(41, 'CABLE MOD', '/store/images/categories/category_41.png',5),
	(42, 'IPHONE', '/store/images/categories/category_42.png',6),
	(43, 'ANDROID', '/store/images/categories/category_43.png',6),
	(44, 'OPERATING SYSTEM', '/store/images/categories/category_44.png',7),
	(45, 'SOFTWARE', '/store/images/categories/category_45.png',7),
	(46, 'GIFT CARD', '/store/images/categories/category_46.png',7),
	(47, 'PC GAMES', '/store/images/categories/category_47.png',7),
	(48, 'CONSOLE ACCESSORIES', '/store/images/categories/category_48.png',8),
	(49, 'PLAYSTATION', '/store/images/categories/category_49.png',8),
	(50, 'XBOX', '/store/images/categories/category_50.png',8);

