FROM python:3.10-alpine
WORKDIR /server
COPY requirements.txt .
RUN apk add --no-cache mariadb-dev build-base
RUN pip install -r requirements.txt
RUN apk del mariadb-dev build-base
COPY . .
ENV DJANGO_SETTINGS_MODULE="storefront.settings.prod"
EXPOSE 8000 
ENTRYPOINT python manage.py migrate && python manage.py seed_db && python manage.py runserver 0.0.0.0:8000