# Generated by Django 4.2.7 on 2023-11-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('category', 'name')},
        ),
    ]
