# Generated by Django 4.2.7 on 2023-11-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_variation_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unite_price',
            new_name='unit_price',
        ),
    ]
