# Generated by Django 4.2.7 on 2023-11-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_discount_end_date_alter_discount_start_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
