# Generated by Django 4.2.7 on 2023-12-05 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_order_status_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='base_unit_price',
        ),
        migrations.AlterField(
            model_name='discount',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
