# Generated by Django 5.0 on 2023-12-14 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_orderitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconfiguration',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variation'),
        ),
    ]
