# Generated by Django 5.0 on 2023-12-22 03:21

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_customer_user_alter_productconfiguration_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default='1', upload_to='store/images/categories', validators=[store.validators.validate_file_size]),
            preserve_default=False,
        ),
    ]
