# Generated by Django 5.0.1 on 2024-01-26 16:00

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_compare_customer_alter_wish_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(default=' ', upload_to='store/images/products', validators=[store.validators.validate_file_size]),
            preserve_default=False,
        ),
    ]
