# Generated by Django 5.0.1 on 2024-01-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_productinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='adress',
            name='is_default',
        ),
        migrations.AddField(
            model_name='adress',
            name='adress',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='country',
            field=models.CharField(default='sdqf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='first_name',
            field=models.CharField(default='DQFGd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='last_name',
            field=models.CharField(default='QDSF', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='phone_number',
            field=models.CharField(default='QSDfqsdf', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.adress')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.adress')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='store.customer')),
            ],
        ),
    ]
