# Generated by Django 5.0.1 on 2024-01-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='adress',
            new_name='address',
        ),
    ]
