# Generated by Django 5.0.1 on 2024-01-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_rename_adress_adress_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_adress',
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
