# Generated by Django 5.0.1 on 2024-02-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_address_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
